### PR TITLE
Feat: Instrument await using await-tree

### LINKED ISSUE #580: [Feature]: Instrument the execution path of the command (i.e. `fast_path` or `slow_path`)
### Description about the feature

Instrument the execution path of the command (i.e. `fast_path` or `slow_path`).
Beneficial for debugging.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Harsh1s**
Signed-off-by: Harsh Raj <thisishraj@gmail.com>

* what problem are you trying to solve? (or if there's no problem, what's the motivation for this change?)
-> FIxes #580 
-> Currently, some simple information is logged to display the execution path of the command. This uses more detailed information to show this process (i.e. use await-tree to indicate the duration of each await.).

* what changes does this pull request make?
-> Makes use of `instrument_await` within functions annotated with the #[instrument] macro to add more detailed async tracing.

* are there any non-obvious implications of these changes? (does it break compatibility with previous versions, etc)
-> No

### CODE REVIEW

**Comment by Harsh1s** [comment]
@iGxnon I'm not sure if these are the correct changes that you were looking for, right now I have just added `instrument_await` to all the functions with `instrument` macro. From my reading, this should be enough for the functions for which tracing has already been setup with `instrument` macro. I'll give my best to learn more and make changes if these are not enough, thanks for your patience!

Also, I'll fix the DCO.

**Comment by iGxnon** [comment]
It seems that some validations are not passing. Please check your code and provide an example output if possible.

**Comment by Harsh1s** [comment]
> It seems that some validations are not passing. Please check your code and provide an example output if possible.

Sure, I'll report back with some output. Thanks for the help!

**Comment by Harsh1s** [comment]
@iGxnon Sorry for not being able to devote my time properly for this issue, was busy with some stuff. From what I can see, I'm failing the codecov/project check. Could you suggest some changes that I could make to pass the test?

**Comment by Phoenix500526** [comment]
Hello, @Harsh1s!  I pulled down this pr and found that the signed-off-by information was lost. That's the reason behind the DCO failure. I recommend rebasing your commit on the latest commit on the master branch instead of merging them directly.

**Comment by Harsh1s** [comment]
Hello there @Phoenix500526 , apologies for accidently closing this issue while fixing the DCO. I opened a new PR instead of this one. I'll take care of rebasing from next time. Thanks!

**Pull request closed without merging**
