### PR TITLE
feat: Added validation for --client-listen-urls and --peer-listen-urls

### PR DESCRIPTION
**Pull request by ChaudharyRaman**
This PR resolved this issue: https://github.com/xline-kv/Xline/issues/691
Please briefly answer these questions:

* what problem are you trying to solve? (or if there's no problem, what's the motivation for this change?)
 During the startup process of Xline, certain essential command-line parameters such as --member and --storage-engine are checked. and there is a lack of validation for `--client-listen-urls `and `--peer-listen-urls`
 Here's how it looks -
fix_cli
fix--help

* what changes does this pull request make?

* are there any non-obvious implications of these changes? (does it break compatibility with previous versions, etc)

### CODE REVIEW

**Comment by ChaudharyRaman** [comment]
@Phoenix500526 @iGxnon  Please review this PR. I closed the previous one and remove unnecessary commits and also just wanted to push from proper PR branch name from my local. Please tell me if there is anytime more to be done for this PR.

**Comment by ChaudharyRaman** [comment]
@Phoenix500526 is their any order in which a particular arguments needed to be shown, like right now `--client-listen-urls `and `--peer-listen-urls` are first and then rest of the flags, i will change if required.
While playing with Xline, i found a small `ip-address` issue with the quick_start.sh script for `prometheus` and quick-start DOC. Should i raise a issue for this or are we going to change the quick_start soon in this issue https://github.com/xline-kv/Xline/issues/692.

**Review by Phoenix500526 — APPROVED** [review]
LGTM

**Comment by Phoenix500526** [comment]
> @Phoenix500526 is their any order in which a particular arguments needed to be shown, like right now `--client-listen-urls `and `--peer-listen-urls` are first and then rest of the flags, i will change if required. While playing with Xline, i found a small `ip-address` issue with the quick_start.sh script for `prometheus` and quick-start DOC. Should i raise a issue for this or are we going to change the quick_start soon in this issue #692.

Is the issue you mentioned above described in issue #692? If not, I think it's better to initiate a new issue to describe it.

**Comment by ChaudharyRaman** [comment]
Thanks @Phoenix500526 .Got it! I will raise a issue for this although its just a minor fix.

**Review by bsbds — APPROVED** [review]

**Pull request merged**
