### PR TITLE
feat: move id barrier to utils

### PR DESCRIPTION
**Pull request by bsbds**
Make `IdBarrier` reusable

Please briefly answer these questions:

* what problem are you trying to solve? (or if there's no problem, what's the motivation for this change?)

* what changes does this pull request make?

* are there any non-obvious implications of these changes? (does it break compatibility with previous versions, etc)

### CODE REVIEW

**Review by Phoenix500526 — COMMENTED** [review]
There is another barrier named `IndexBarrier` in `xline::server::barrier`. Shall we move it into `utils::barrier`?

**Comment by bsbds** [comment]
> There is another barrier named `IndexBarrier` in `xline::server::barrier`. Shall we move it into `utils::barrier`?

It will be removed in #857

**Review by Phoenix500526 — APPROVED** [review]
LGTM，please squash these commits into one

**Comment by CrystalAnalyst** [comment]
LGTM

**Review by CrystalAnalyst — APPROVED** [review]

**Pull request merged**
