### PR TITLE
Push the latest image on push master.

### PR DESCRIPTION
**Pull request by liangyuanpeng**
Please briefly answer these questions:

* what problem are you trying to solve? (or if there's no problem, what's the motivation for this change?)

Push the latest image for let people can be experience the master branch function in advance.

* what changes does this pull request make?

* are there any non-obvious implications of these changes? (does it break compatibility with previous versions, etc)

### CODE REVIEW

**Review by rogercloud — APPROVED** [review]

**Comment by Phoenix500526** [comment]
IMO, it's better to provide a script to build the latest image from the master branch rather than to build an image from the master branch and push it into our image repo. It will upload many images that are unstable to our image repo. It may not be a good practice.

**Comment by Phoenix500526** [comment]
BTW, I am confused with these three workflows: merge_image.yml, release.yml, and docker_image.yml. The docker_image.yml workflow has not been triggered since it was created. Do you have any interest in refactoring them?

**Comment by liangyuanpeng** [comment]
> It will upload many images that are unstable to our image repo.

It only "one" image---latest, the user should know that this is "The latest" image and not a stable image. I just want to use it and don't want to build it, i would say this is a universal need.


> The docker_image.yml workflow has not been triggered since it was created.

I used this workflow to created the image for PR [fix: xline watcher will loss event ](https://github.com/xline-kv/Xline/pull/678)  on my fork repo, see https://github.com/liangyuanpeng/Xline/actions/runs/8244904769

> Do you have any interest in refactoring them?

please create a issue for it and i will pick it up when i have the time, or welcome other one contribute.

**Review by Phoenix500526 — APPROVED** [review]
LGTM

**Pull request merged**
